name: Deploy Using SSH

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: list files
      run: |
        apt install traceroute
        pwd
        ls -l
    - name: Trace Route to SSH Server
      run: traceroute 192.168.0.170

    - name: Run My Custom Action
      uses: josue-r/ssh-gha@main
      with:
        # Your action's inputs go here
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: 'echo "hello"'